### ISSUE TITLE
Crash version 1.6.1

### ISSUE THREAD

**Issue by lUjek-Sh** [Samuel-Unknown/Gallery-Image-Picker#25] opened 2023-09-21 09:19 UTC
```
Fatal Exception: java.lang.NullPointerException:
       at com.samuelunknown.galleryImagePicker.domain.useCase.getFoldersUseCase.GetFoldersUseCaseImpl$execute$2.invokeSuspend(GetFoldersUseCaseImpl.kt:34)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Samuel-Unknown** [comment] 2023-09-22 11:43
Please give me more information how to reproduce it. When it happens?

**Comment by lUjek-Sh** [comment] 2023-09-22 12:01
> Please give me more information how to reproduce it. When it happens?

I don’t know how to reproduce this crash. I don’t have this crash. I saw this crash in Firebase when I updated the library in my project.

**Comment by Samuel-Unknown** [comment] 2023-10-03 11:14
Since there is no obvious case for reproducing this crash, I am closing the issue. If you find a way to reproduce it please re-open it.

**Comment by lUjek-Sh** [comment] 2023-10-03 11:19
Я вроде как исправил вот так
![Снимок экрана 2023-10-03 в 14 17 01](https://github.com/Samuel-Unknown/Gallery-Image-Picker/assets/64215831/7aa4566a-4a92-48bb-88bb-806174831be8)

**Comment by Samuel-Unknown** [comment] 2023-10-03 11:59
Thank you, I'll check it later on my side 👍

**Closed** 2023-10-03 17:52 UTC
